// Wire protocol between the server half (Node, on the PC) and the client half
// (React, on the Car Thing).
//
// Source data is whatever PC Health Checker last wrote to
//   C:\Apps\Portable\PC Health\PCHealth-data\history\health-*.json
// generated by the "PC Health Check" scheduled task running `PC Health.exe --scan`.

export type CategoryStatus = "OK" | "INFO" | "WARN" | "CRIT";

/** date (YYYY-MM-DD or YYYY-MM) -> event count */
export type EventSeries = Record<string, number>;

/**
 * The checker emits a per-category `Metrics` bag whose shape differs by
 * category. The previous version of this file dropped it entirely, which is why
 * the screen could only ever render prose. The time series in here is the whole
 * reason this app is not just a smaller copy of the desktop report.
 */
export type CategoryMetrics = {
  /** WHEA + Stability both carry these. Days are the 120d window. */
  byDay?: EventSeries;
  byMonth?: EventSeries;
  /** WHEA */
  corrected?: number;
  corrected_30d?: number;
  uncorrected?: number;
  /** Stability */
  kp41?: number;
  kp41_30d?: number;
  bsod?: number;
  bsod_30d?: number;
  /** Memory */
  totalGB?: number;
  usedPct?: number;
  /** Reliability */
  avg14?: number;
  latest?: number;
  /** Uptime */
  uptimeDays?: number;
  slowBoots?: number;
  /** Devices */
  real?: number | null;
  benign?: number | null;
  /** Storage */
  drives?: Drive[];
  smart?: Smart[];
};

export type Volume = { id: string; freePct: number; freeGB: number };
export type Drive = {
  name: string;
  gb: number;
  media: string;
  health: string;
  vols: Volume[];
};
export type Smart = { name: string; temp: number | null; wear: number | null };

export type HealthCategory = {
  name: string;
  status: CategoryStatus;
  penalty: number;
  details: string[];
  metrics: CategoryMetrics;
};

export type HealthReport = {
  timestamp: string;
  /** The checker's own score, which is rounded. */
  score: number;
  /**
   * Score with the rounding undone: 100 - sum(penalties), to one decimal.
   * The checker reports 100 while still flagging a WARN worth 0.3, so the
   * headline number and the status colour disagreed. This is the honest one:
   * 100 now means literally nothing was deducted.
   */
  exactScore: number;
  grade: string;
  headline: string;
  days: number;
  computer: string;
  cpu: string;
  /** Physical core count parsed out of the CPU string, e.g. "(10C/20T)" -> 10. */
  cores: number;
  os: string;
  bios: string;
  categories: HealthCategory[];
};

export type HealthPayload = {
  report: HealthReport | null;
  updated: string;
  error?: string;
};

export enum SERVER_TYPE {
  HEALTH = "pcHealth",
}

export enum CLIENT_TYPE {
  HEALTH = "pcHealthRequest",
}

export type ToClientData = {
  type: SERVER_TYPE.HEALTH;
  request: "update";
  payload: HealthPayload;
};

export type ToServerData = {
  type: CLIENT_TYPE.HEALTH;
  request: "get";
  payload: undefined;
  clientId?: string;
};
