// Wire protocol between the server half (Node, on the PC) and the client half
// (React, on the Car Thing).
//
// Source data is whatever PC Health Checker last wrote to
//   C:\Apps\Portable\PC Health\PCHealth-data\history\health-*.json
// generated by the "PC Health Check" scheduled task running `PC Health.exe --scan`.

export type CategoryStatus = "OK" | "INFO" | "WARN" | "CRIT";

/** date (YYYY-MM-DD or YYYY-MM) -> event count */
export type EventSeries = Record<string, number>;

/**
 * The checker emits a per-category `Metrics` bag whose shape differs by
 * category. The previous version of this file dropped it entirely, which is why
 * the screen could only ever render prose. The time series in here is the whole
 * reason this app is not just a smaller copy of the desktop report.
 */
export type CategoryMetrics = {
  /** WHEA + Stability both carry these. Days are the 120d window. */
  byDay?: EventSeries;
  byMonth?: EventSeries;
  /** WHEA */
  corrected?: number;
  corrected_30d?: number;
  uncorrected?: number;
  /** Stability */
  kp41?: number;
  kp41_30d?: number;
  bsod?: number;
  bsod_30d?: number;
  /** Memory */
  totalGB?: number;
  usedPct?: number;
  /** Reliability */
  avg14?: number;
  latest?: number;
  /** Uptime */
  uptimeDays?: number;
  slowBoots?: number;
  /** Devices */
  real?: number | null;
  benign?: number | null;
  /** Storage */
  drives?: Drive[];
  smart?: Smart[];
  /**
   * Thermals. Only present when HWiNFO is running with Shared Memory Support
   * enabled - the checker reads its live shared memory block. Without it the
   * whole category comes through empty, which is why this used to be blank.
   */
  cores?: CoreTemp[];
  hotCore?: number;
  cpuMaxC?: number;
  gpuC?: number;
  /** "C" or "F" - the checker's display preference, worth honouring. */
  unit?: string;
  cpuMaxDisp?: string;
};

/** One physical core's temperature, in Celsius, as HWiNFO reports it. */
export type CoreTemp = { n: number; c: number };

export type Volume = { id: string; freePct: number; freeGB: number };
export type Drive = {
  name: string;
  gb: number;
  media: string;
  health: string;
  vols: Volume[];
};
export type Smart = { name: string; temp: number | null; wear: number | null };

export type HealthCategory = {
  name: string;
  status: CategoryStatus;
  penalty: number;
  details: string[];
  metrics: CategoryMetrics;
};

export type HealthReport = {
  timestamp: string;
  /** The checker's own score, which is rounded. */
  score: number;
  /**
   * Score with the rounding undone: 100 - sum(penalties), to one decimal.
   * The checker reports 100 while still flagging a WARN worth 0.3, so the
   * headline number and the status colour disagreed. This is the honest one:
   * 100 now means literally nothing was deducted.
   */
  exactScore: number;
  grade: string;
  headline: string;
  days: number;
  computer: string;
  cpu: string;
  /** Physical core count parsed out of the CPU string, e.g. "(10C/20T)" -> 10. */
  cores: number;
  os: string;
  bios: string;
  categories: HealthCategory[];
};

/** One category's status moving between two scans. */
export type StatusChange = {
  name: string;
  from: CategoryStatus;
  to: CategoryStatus;
  /** True when the move is toward trouble (OK -> WARN), false when it recovers. */
  worse: boolean;
};

/**
 * What changed since the previous scan.
 *
 * A snapshot answers "how is it now", which a glanceable screen is bad at
 * making meaningful - 93 means nothing without knowing it was 100 yesterday.
 * This is the part worth reading from across the room.
 */
export type HealthDelta = {
  /** Timestamp of the report being compared against. */
  since: string;
  /** exactScore now minus exactScore then. Negative means it got worse. */
  scoreDelta: number;
  /** New corrected WHEA errors inside the 30-day window since the last scan. */
  newWhea30d: number;
  /** New unexpected shutdowns / BSODs in the 30-day window. */
  newCrashes30d: number;
  /** Categories whose status changed between the two scans. */
  changes: StatusChange[];
};

export type HealthPayload = {
  report: HealthReport | null;
  /** Null when there is no earlier report to compare against. */
  delta: HealthDelta | null;
  updated: string;
  error?: string;
};

export enum SERVER_TYPE {
  HEALTH = "pcHealth",
}

export enum CLIENT_TYPE {
  HEALTH = "pcHealthRequest",
}

export type ToClientData = {
  type: SERVER_TYPE.HEALTH;
  request: "update";
  payload: HealthPayload;
};

export type ToServerData = {
  type: CLIENT_TYPE.HEALTH;
  request: "get";
  payload: undefined;
  clientId?: string;
};
